"""P0 intake identification service (R17.5 WP-1).

The P0 stage is a target-driven Node Worker Agent loop (AGENTS §2.3): deterministic
code only *gathers* facts (clone / list files / read / count / encoding / redact);
IDENTIFICATION — key-file judgement, tech stack / environment interpretation,
availability A/B/C, migration-intent归纳, DB entry/dialect interpretation, entry-point
judgement, P1 task planning, gap自我发声 — is done by the LLM (Node Worker Agent) via
ModelGateway (D-098, no hardcoded model/endpoint). This mirrors the P2 AssessmentService
范式 (R10-2 Q-R10-2): LLM is REQUIRED — no available model → status="blocked"
(reason=no_model_key), NO rule-based fallback (D-097/公理3). An honest blocked beats a
fake rule-derived intake.

The general field ANCHORS are a stable platform schema; the field VALUES (sample层) are
generated by the LLM per project — never hardcoded sample values (§2.3, §10-26). Missing
fields are honestly recorded as null + reason (never fabricated); blind spots are actively
voiced (公理3). Deep business semantics / field-level DB schema stay in P1/P2.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from typing import Any, Optional

logger = logging.getLogger("rebuild.intake_service")

# 模型全失败中断时前端可采取操作（复用 gateway 单一事实源）。
from app.services.model_gateway import MODEL_UNAVAILABLE_USER_ACTIONS as _MODEL_USER_ACTIONS
# V26.2 返工批次二（Q-B2-1 / Q-B2-2）：共享的截断诊断 + "不设即无上限"的 env 旋钮解析。
from app.services.stage_agent_loop import (
    DEFAULT_STAGE_TIMEOUT_SECONDS as _STAGE_TIMEOUT,
    diagnose_parse_failure as _diagnose_parse_failure_shared,
    log_parse_failure as _log_parse_failure,
    optional_int_env,
)

# `B-V262-TOKENBUDGET-UNFIXED-4`（P0）：真实规模真跑（MicroOA 1018 文件 / 197,447 行）实测
# 本调用的 completion **触顶原硬编码 max_tokens=16384**（call_log `scall_1470a9bb8b35`
# completion_tokens=16383）→ P0 识别 JSON 中途截断 → `identification` 只剩
# `{"parse_error": true, "raw": "```json\n{…"}` → 12 个识别键全落 null。
# 用户 2026-09-16 裁决 Q-B2-1：**不再抬高天花板，直接取消平台侧硬预算**（批次 F 把另外几处抬到
# 32768/16384 后，未抬的四处又在 16384 撞顶 —— 抬高只是把天花板挪一格）。
# 现口径：默认 None ⇒ 请求体无 max_tokens 键；上限交还给模型自身最大输出长度 + adapter 三层
# 时间护栏。旋钮 `P0_INTAKE_MAX_TOKENS` 保留作成本失控时的逃生阀（不设即不设上限）。
# 实测触顶值 16383 保留在此仅作**历史依据留痕**，不再作为默认值。
_INTAKE_MAX_TOKENS = optional_int_env("P0_INTAKE_MAX_TOKENS")

# LLM-produced identification fields (通用锚点，样本值由 LLM 生成)。materialization/
# repository_metadata/file_count 等由采集提供，不在此列。
INTAKE_IDENTIFICATION_FIELDS = [
    "key_files", "source_environment_clues", "database_entry",
    "availability_classification", "migration_intent", "entry_points",
    "p1_intake_tasks", "missing_information", "questions_for_user",
    "uncertainty", "primary_language", "detected_stack",
]

_SYSTEM_PROMPT = (
    "你是 rebuild 平台的 P0 接入识别 Agent（Node Worker Agent）。平台已用确定性工具【采集】了目标"
    "项目的事实包（文件清单、扩展名计数、关键文件候选与其脱敏原文、git 元数据、SQL 元数据、用户"
    "迁移意图原文、目标运行环境）。你的职责是【识别与解读】——不是重新采集，而是基于事实包推理。\n"
    "严格输出 JSON，键为：\n"
    "  key_files（数组，每项 {path, why_key}：从采集的 key_files 候选中判定哪些是真正关键的构建/"
    "配置/入口/DB 文件，按项目技术栈判断，引用真实存在的候选路径，勿杜撰）；\n"
    "  source_environment_clues（对象：languages, frameworks, runtimes, web_host, databases, orm, "
    "project_type, deployment_clues——对采集的脱敏原始属性/原文推理，泛化任意技术栈；连接串等敏感值"
    "不得回显）；\n"
    "  database_entry（对象 {present, entry, dialect, encoding, scale, note}：采集已给规模/编码，你"
    "解读方言与入口；字段级 schema 留 P1，note 标 NOT_DONE_IN_P0）；\n"
    "  availability_classification（对象 {class: A|B|C, label, reasoning: [证据链]}：A=源码可用且原环境"
    "已验证运行[需实跑证据]；B=源码可用未验证运行；C=源码/关键文件缺失。当前环境无法实跑不作为降级"
    "为 C 的依据；无实跑证据不判 A）；\n"
    "  migration_intent（对象 {text, source, confidence, decision_status}：归纳用户迁移意图原文，不裁决"
    "迁移路线；source=user_intent, confidence=unverified, decision_status=pending_p2_assessment；意图缺失"
    "则 text=null 且 note=not_provided_at_p0，不编造）；\n"
    "  entry_points（数组，每项 {path, kind}：据 key_files/结构/计数判定真实应用入口，勿把第三方 vendor/"
    "examples 里的 index.js/main.js 误判为入口）；\n"
    "  p1_intake_tasks（数组，每项 {category, task, scope_ref}：按【本项目真实结构】生成可执行的 P1 建档"
    "任务清单，防 P1 空转；scope_ref 引用真实目录/计数，任务数量与类别随项目而定，不套固定模板）；\n"
    "  missing_information（数组，字符串：研判缺失的关键信息，如许可/目标数据库/目标环境等）；\n"
    "  questions_for_user（数组，字符串：需要用户澄清的问题）；\n"
    "  uncertainty（数组，每项 {area, detail}：主动发声你的识别盲区与不确定项，禁止 0-gap 掩盖）；\n"
    "  primary_language（字符串或 null：据文件分布 + 构建/工程文件综合判定主语言，不因静态资源/vendor "
    "示例文件数量多而误判；无法确定则 null）；\n"
    "  detected_stack（数组，字符串：识别到的技术栈，按重要性排序）。\n"
    "硬约束：所有样本值必须来自事实包推理，不得凭空编造；缺失字段诚实标 null + 原因；深度业务语义/"
    "字段级 DB schema 不在 P0 做（标 NOT_DONE_IN_P0）；全程脱敏，任何密钥/连接串/口令值一律不输出。"
)

# 连接串/敏感属性的补充脱敏（在采集读取原文时二次防护，D-032）。
_CONN_STRING_PATTERNS = [
    re.compile(r'(connectionString\s*=\s*")[^"]*(")', re.IGNORECASE),
    re.compile(r"(connectionString\s*=\s*')[^']*(')", re.IGNORECASE),
]


@dataclass
class IntakeResult:
    status: str                       # completed / blocked / failed
    reason: str = ""
    identification: dict = field(default_factory=dict)   # LLM-produced identification fields
    model_used: Optional[str] = None
    evidence: list = field(default_factory=list)
    context_refs: list = field(default_factory=list)
    skill_refs: list = field(default_factory=list)
    # 模型全失败强制中断时的「已尝试模型链路」+ 结构化错误分类 + 用户可采取操作（透传前端）。
    attempted_chain: list = field(default_factory=list)
    model_error_category: str = ""
    model_user_actions: list = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "status": self.status,
            "reason": self.reason,
            "identification": self.identification,
            "model_used": self.model_used,
            "evidence": self.evidence,
            "context_refs": self.context_refs,
            "skill_refs": self.skill_refs,
            "attempted_chain": self.attempted_chain,
            "model_error_category": self.model_error_category,
            "model_user_actions": self.model_user_actions,
        }


class IntakeService:
    """P0 identification via ModelGateway. `gateway` injectable for tests (blocked
    path + parsing without a live LLM), mirroring AssessmentService (no mock in the
    production path)."""

    def __init__(self, *, gateway=None, tracer=None, auditor=None):
        self._gateway = gateway
        self.tracer = tracer
        self.auditor = auditor

    def _get_gateway(self):
        if self._gateway is not None:
            return self._gateway
        from app.dependencies import get_services
        return get_services().model_gateway

    async def identify(
        self,
        project_id: str,
        *,
        facts: dict,
        run_id: Optional[str] = None,
        stage: str = "p0",
        strategy_id: str = "system-default",
        system_prompt: Optional[str] = None,
        skill_body: str = "",
        context_package: Optional[dict] = None,
    ) -> IntakeResult:
        """Run the P0 identification. Returns IntakeResult (status ∈ completed/blocked/failed).

        `facts` is the deterministic收集事实包 (source_index summary + redacted key-file
        contents + git meta + SQL meta + migration intent/target). The assembled
        `system_prompt` (C0-C6 governance/product/architecture) and `skill_body`
        (P-codebase-onboarding SKILL.md) are combined with the P0 identification output
        contract so the model receives unified context AND the strict JSON schema.
        """
        gw = self._get_gateway()

        # WP-5 (Q-R10-2扩展 P0): no available model → blocked, no rule fallback. 就绪度
        # 预检给出候选模型链路，即便一次调用都未发生也让前端显式看到考察过的模型链路。
        readiness = gw.stage_model_readiness(strategy_id=strategy_id, project_id=project_id,
                                             require_tool_calling=True)
        if not readiness.get("available"):
            self._trace("P0 intake blocked: no model", project_id, run_id, stage)
            return IntakeResult(
                status="blocked",
                reason=("no_model_key: P0 识别需要 LLM 支持，请配置有效 API Key（P0 不降级为规则识别）"
                        f"；{readiness.get('reason','')}"),
                attempted_chain=readiness.get("attempted_chain", []),
                model_error_category="model_unavailable",
                model_user_actions=readiness.get("user_actions", []))

        context_refs, skill_refs = self._context_refs(context_package)
        # system content: 统一上下文（若有）+ Skill 正文（若有）+ P0 识别输出契约（契约放最后，
        # 保证 JSON schema 指令不被冲淡）。
        head_parts = [p for p in (system_prompt, skill_body) if p]
        system_content = ("\n\n---\n\n".join(head_parts) + "\n\n---\n\n" + _SYSTEM_PROMPT
                          if head_parts else _SYSTEM_PROMPT)

        # 批2 (D-110): P0 从单次 chat → 工具循环 Node Worker Agent。事实包仍作为 user 提示帮助，
        # 但 agent 可按需 list_files/code_grep/fs_read 探读真实源、多轮推理，末轮产出结构化识别
        # 契约（契约不变，D-108）。走 call_stream 天然读项目模型选择（global_model_ref）。
        from app.services.stage_agent_loop import run_stage_tool_loop
        loop = await run_stage_tool_loop(
            gw, system_content=system_content, user_content=self._build_user_prompt(facts),
            project_id=project_id, run_id=run_id or "", stage=stage,
            strategy_id=strategy_id, max_tokens=_INTAKE_MAX_TOKENS, temperature=0.3,
            tracer=self.tracer)
        if loop["status"] != "completed":
            reason = loop.get("error_message") or loop.get("error_category") or "model_call_failed"
            self._trace(f"P0 intake model call not completed: {reason}", project_id, run_id, stage)
            return IntakeResult(status="failed", reason=str(reason),
                                model_used=loop.get("model_used"),
                                attempted_chain=loop.get("attempted_chain", []),
                                model_error_category=loop.get("error_category", "model_unavailable"),
                                model_user_actions=_MODEL_USER_ACTIONS)

        parsed = self._parse(loop.get("content", ""))
        model_used = loop.get("model_used")
        # ── 解析失败守卫（`B-ACC-P0-PARSEERROR-STILL-ACCEPTED` 解除条件 ①）────────────
        # 真实规模真跑实测：识别输出不可解析时本方法此前**无条件** return status="completed"，
        # 于是 12 个识别键全落 null、阶段却报 `verdict: accepted / issues: []` —— 把"不可用"
        # 谎报为"可用"。参照实现是 P2 侧 `stage_handlers.py` 的 `unparseable_output` 守卫
        # （同一失败模式，P2 有守卫、P0 没有）。
        # 这里返回**非完成态**：图编排据此触发真返工 —— ValidationAgent 见 declared !=
        # "completed" 即 passed=False（`validation_agent.py` 的综合裁决），ReviewPass 因此重跑
        # 一轮 WorkAgent（真的重新识别，不是只记一笔），仍不通过才升级为 Gate。
        # reason 前缀 `unparseable_output:` 与既有 `no_model_key:` 同范式（机器可判、人可读）；
        # **不含** "no_model_key" 字样、attempted_chain 留空 ⇒ 不会被误判为模型全失败中断。
        # identification 原样带出（含 parse_error / raw / parse_diagnosis），使失败现场能直接
        # 指认"是不是被截断"，而不是只留一句"解析失败"。
        # ⚠ 有意**不设** `model_error_category="output_contract_parse_error"`：该分类会让
        # `stage_retry.is_transient_stage_failure()` 把本次失败判为可重试，于是整个 P0 阶段会先被
        # 自动重跑最多 2 次（`STAGE_TRANSIENT_MAX_RETRIES`），再叠加 ReviewPass 的 2 轮返工 ⇒ 最坏
        # 6 次完整 P0（每次都是真实 LLM 成本）。ReviewPass 的返工已经覆盖"重试结构化输出"这一诉求，
        # 故不再叠加阶段级重试。若将来判定 P0 也应像 P3 那样走阶段级重试，须连同成本一并评估后再加。
        if parsed.get("parse_error"):
            diagnosis = parsed.get("parse_diagnosis") or {}
            truncated = bool(diagnosis.get("suspected_truncation"))
            self._trace("P0 intake identification unparseable（非完成态，触发返工）",
                        project_id, run_id, stage)
            return IntakeResult(
                status="failed",
                reason=("unparseable_output: P0 识别输出无法解析为结构化 JSON"
                        f"（疑似截断={truncated}；诊断见 identification.parse_diagnosis）"
                        "——不得据此判阶段完成（D-097/公理3）"),
                identification=parsed, model_used=model_used,
                context_refs=context_refs, skill_refs=skill_refs)
        # 目标运行环境是用户输入采集（非识别），由采集直接透传进 intake（migration_target）。
        parsed.setdefault("migration_target", facts.get("migration_target"))
        self._trace("P0 intake completed (LLM identification)", project_id, run_id, stage)
        return IntakeResult(
            status="completed", identification=parsed, model_used=model_used,
            context_refs=context_refs, skill_refs=skill_refs,
        )

    @staticmethod
    def _context_refs(context_package: Optional[dict]) -> tuple[list, list]:
        if not context_package:
            return [], []
        trace = context_package.get("assembly_trace", {}) or {}
        context_refs = list(trace.get("layers_assembled", []))
        skill_refs = [s.get("skill_id") or s.get("name")
                      for s in (context_package.get("skills") or [])
                      if s.get("skill_id") or s.get("name")]
        return context_refs, skill_refs

    def _build_user_prompt(self, facts: dict) -> str:
        """Build the user message from the deterministic收集事实包 (bounded, redacted)."""
        # facts is already redacted/bounded by the caller (RealP0Handler collection).
        blob = json.dumps(facts, ensure_ascii=False, default=str)
        if len(blob) > 24000:      # 采集事实包上限，防超长（诚实截断并声明）
            blob = blob[:24000] + '\n…[事实包超长已截断，请就已给事实推理并在 uncertainty 中声明截断]'
        return (
            "以下是平台确定性工具采集的目标项目【事实包】（已脱敏、已按大小写不敏感列举、依赖/入口"
            "为全候选交你判定）。请据此完成 P0 接入识别，严格输出上述 JSON。\n\n"
            f"事实包：\n{blob}\n\n"
            "要求：key_files/entry_points 只能引用事实包中真实存在的候选路径（勿杜撰）；样本值全部来自"
            "事实包推理；缺失诚实标 null + 原因；主动在 uncertainty 中发声识别盲区。"
        )

    def _parse(self, content: str) -> dict:
        """Parse the LLM JSON output defensively into the identification fields.

        批2: uses the robust extractor (handles prose-wrapped / fenced JSON from the tool
        loop).

        `B-ACC-P0-PARSEERROR-STILL-ACCEPTED` 解除条件 ③（声称与实现不符的订正）：本 docstring
        原文自称 `Unparseable → honest parse_error marker (NodeLoop ReviewPass retries)`，
        日志原文亦印"（返工重试结构化输出）"—— 但实测**当时并没有那个重试**：`identify()` 无条件
        置 status="completed"，图直接进 Gate。现已改为**真的**返非完成态（见 `identify()` 的解析
        失败守卫），返工由 ValidationAgent → ReviewPass 真实触发。措辞按"实现什么就说什么"订正：
        本方法只负责**产出可诊断的 parse_error 标记**，返工与否由 `identify()` 的守卫与图编排决定。

        V26.2 返工批次二（甲 ②）：本处此前**完全没有截断诊断**，失败现场只能看到"输出非合法
        JSON"，看不出"因为被砍断" —— 这正是验收 agent 把真因误归为"模型输出质量问题"的直接原因。
        现接入共享诊断（`suspected_truncation` / `truncation_signals`）。
        """
        from app.services.stage_agent_loop import extract_json_object
        data = extract_json_object(content)
        if data is not None:
            return data
        text = (content or "").strip()
        diagnosis = _diagnose_parse_failure_shared(
            text, max_tokens=_INTAKE_MAX_TOKENS, timeout_s=_STAGE_TIMEOUT,
            env_knobs="P0_INTAKE_MAX_TOKENS")
        _log_parse_failure(logger, "P0 intake", diagnosis)
        return {"parse_error": True, "raw": text[:2000], "parse_diagnosis": diagnosis}

    def _trace(self, summary: str, project_id, run_id, stage) -> None:
        if self.tracer is None:
            return
        try:
            self.tracer.write("model_call", action="p0_intake", summary=summary,
                              project_id=project_id, run_id=run_id, stage=stage)
        except Exception:
            logger.debug("P0 intake trace 写入失败（advisory）", exc_info=True)


def redact_config_text(text: str) -> str:
    """采集层脱敏（D-032）：连接串值 + api_key/secret/password/token 一律 [REDACTED]。
    用于把关键文件原文喂给 LLM 前的二次防护——绝不把密钥/连接串值送入模型或落盘。"""
    if not text:
        return text
    from app.services.security_authorization import redact_secrets
    out = text
    for pat in _CONN_STRING_PATTERNS:
        out = pat.sub(r"\1[REDACTED]\2", out)
    return redact_secrets(out)
