"""P1 profiling (建档) identification service (R17.5 P1 WP-1).

The P1 stage is a target-driven Node Worker Agent loop (AGENTS §2.3), exactly like
P0: deterministic code only *gathers* facts (list files / structure / case-insensitive
candidates / dependency manifest raw contents / config raw / test contents — redacted);
IDENTIFICATION — primary language / tech stack / framework / dependency judgement /
entry-point判定 / config interpretation / infra解读 / module business semantics /
盲区自我发声 — is done by the LLM (Node Worker Agent) via ModelGateway (D-098, no
hardcoded model/endpoint). Mirrors the P0 IntakeService 范式 (do NOT另造框架, D-065):
LLM is REQUIRED — no available model → status="blocked" (reason=no_model_key), NO
rule-based fallback (D-097/公理3).

WP-2 (P1-ARCH-1): P1 REUSES the upstream P0 产物 — P0's LLM-produced intake
identification (primary_language / environment clues / DB / availability) + source_index
— and DEEPENS建档 on top of it. It MUST NOT recompute from scratch or overturn the P0
conclusion silently (病灶: P0 判 C#，旧 P1 确定性误判 JS). If new P1 evidence genuinely
contradicts P0, the model must voice it explicitly in `uncertainty`, not silently flip.

The general field ANCHORS are a stable platform schema; the field VALUES (sample层) are
generated by the LLM per project — never hardcoded sample values (§2.3, §10-26). Missing
fields are honestly recorded as null + reason; blind spots are actively voiced (公理3).
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass, field
from typing import Optional

logger = logging.getLogger("rebuild.profiling_service")

from app.services.model_gateway import MODEL_UNAVAILABLE_USER_ACTIONS as _MODEL_USER_ACTIONS

# D-06（V26.2 总验收真实规模真跑，2026-09-11，批次B）：真实项目（1018 文件 / 197,447 行）上
# 本调用的 completion **恰好 4 次触顶原硬编码 max_tokens=16384**（存档响应头部为
# `{"tech_stack": {"primary_language": "C#"…` 即被砍断）→ 建档识别 JSON 中途截断解析失败 →
# 8 个识别键全部落为 None → stage_handlers 写成"LLM 未产出 xxx（诚实标注）"占位——这正是
# D-05（P1 8/23 域产物为空、独立验收仍判 accepted/0 问题）的真正根因。
# 复用 acceptance_baseline_service 刚建立的 env 可调范式（不新造机制）。
#
# 默认值依据（实测，非拍脑袋）：
#   · 32768 = 触顶值 16384 的 2 倍。acceptance_baseline_service 同批已把静态基线（3 个数组
#     字段）的预算提到 16384（触顶值 6144 的 2.67 倍）；profiling 一次要产出 8 个键
#     （tech_stack/dependency_draft/entry_points/config_inventory/infra_clues/test_inventory/
#     module_structure/uncertainty_manifest），其中 dependency_draft 真实规模下要覆盖 49 个
#     依赖包（D-13 实测计数），内容体量与 R11-7 为 P3 task_plans 设的预算同级，而非
#     acceptance_baseline 的小体量清单，故直接复用平台已有的更高一档（32768），不再另立一个
#     居中的新数字。
#   · 300s：本调用走 run_stage_tool_loop（多轮工具循环，可按需 list_files/fs_read/code_grep
#     探读真实源，不是单次 non-stream 调用），且预算翻倍后单轮生成耗时也会拉长；
#     acceptance_baseline_service 对 16384 预算、单次调用取 240s（依据实测 60-120s 延迟 ×2
#     余量）；profiling 预算是其 2 倍且为多轮工具循环，300s 留出更合理的余量。
# 二者只调请求超时与输出预算，不涉及模型/endpoint 选择（策略仍由 ModelGateway 解析，D-098）。
_PROFILING_MAX_TOKENS = int(os.environ.get("P1_PROFILING_MAX_TOKENS", "32768"))
_PROFILING_TIMEOUT = float(os.environ.get("P1_PROFILING_TIMEOUT", "300"))

# LLM-produced 建档 identification fields (通用锚点，样本值由 LLM 生成)。file_index /
# source_structure / cicd / doc 等由采集提供，不在此列。
PROFILING_IDENTIFICATION_FIELDS = [
    "tech_stack", "dependency_draft", "entry_points", "config_inventory",
    "infra_clues", "test_inventory", "module_structure", "uncertainty_manifest",
]

_SYSTEM_PROMPT = (
    "你是 rebuild 平台的 P1 建档识别 Agent（Node Worker Agent）。平台已用确定性工具【采集】了目标"
    "项目的事实包（文件索引、源码结构、大小写不敏感的依赖清单/配置/测试候选及其脱敏原文、扩展名计数），"
    "并附带【上游 P0 已由 LLM 产出的接入识别结论】（primary_language / 环境线索 / DB 入口 / 可用性）。\n"
    "你的职责是【深化建档】——在 P0 结论之上做更细的项目档案，而不是从零重算或推翻 P0。硬约束：\n"
    "  · 复用 P0 的 primary_language / detected_stack / 环境线索作为基线；若你的证据与 P0 结论一致，"
    "沿用之；若确有新证据与 P0 冲突，不得静默改判——在 uncertainty 中显式登记冲突与你的依据。\n"
    "严格输出 JSON，键为：\n"
    "  tech_stack（对象 {primary_language, languages:[{language, file_count, confidence}], "
    "frameworks:[{framework, confidence, evidence}], build_systems:[{build_system, file}]}：主语言据"
    "扩展名分布+构建/工程文件+框架信号综合判定，不因静态资源(.gif/.css)或 vendor 示例文件数量多而误判；"
    "primary_language 复用 P0 结论，除非有显式冲突登记）；\n"
    "  dependency_draft（对象 {dependencies:[{name, version, source, type}], total, note}：从采集的"
    "依赖清单原文（packages.config/.csproj/pom.xml/*.gradle/requirements.txt/package.json/go.mod/"
    "Cargo.toml/composer.json/Gemfile 等，任意栈）解析依赖，不局限于某几种清单格式）；\n"
    "  entry_points（数组，每项 {path, kind, why}：据结构/关键文件判定真实应用入口，勿把 vendor/"
    "examples 里的 index.js/main.js 误判为入口；.NET WebForms 入口如 Global.asax/*.aspx/*.ashx）；\n"
    "  config_inventory（对象 {configs:[{path, config_type, purpose}], count}：识别配置文件用途，"
    "大小写不敏感，连接串/密钥值绝不回显）；\n"
    "  infra_clues（对象 {infra:[{infra_type, evidence, confidence}], count}：解读数据库/中间件/Web宿主"
    "/外部服务线索，泛化任意技术栈；敏感值脱敏）；\n"
    "  test_inventory（对象 {has_tests, test_directories:[...], test_frameworks:[...], "
    "assertions_understood:[{path, what_it_verifies}], note}：大小写不敏感识别测试目录/框架，并读断言理解"
    "「验证了什么」）；\n"
    "  module_structure（对象 {modules:[{path, role}], is_monorepo, note}：识别模块/包及其业务角色）；\n"
    "  uncertainty_manifest（对象 {evidence_gaps:[{area, detail}], total_gaps}：主动发声你的识别盲区、"
    "与 P0 的冲突、无法判定项，禁止 0-gap 掩盖）。\n"
    "硬约束：所有样本值必须来自事实包/上游推理，不得凭空编造；缺失字段诚实标 null + 原因；深度业务语义/"
    "字段级 DB schema 可留 P2；全程脱敏，任何密钥/连接串/口令值一律不输出。"
)


@dataclass
class ProfilingResult:
    status: str                       # completed / blocked / failed
    reason: str = ""
    identification: dict = field(default_factory=dict)
    model_used: Optional[str] = None
    context_refs: list = field(default_factory=list)
    skill_refs: list = field(default_factory=list)
    attempted_chain: list = field(default_factory=list)
    model_error_category: str = ""
    model_user_actions: list = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "status": self.status,
            "reason": self.reason,
            "identification": self.identification,
            "model_used": self.model_used,
            "context_refs": self.context_refs,
            "skill_refs": self.skill_refs,
            "attempted_chain": self.attempted_chain,
            "model_error_category": self.model_error_category,
            "model_user_actions": self.model_user_actions,
        }


class ProfilingService:
    """P1 建档 identification via ModelGateway. `gateway` injectable for tests
    (blocked path + parsing without a live LLM), mirroring IntakeService/AssessmentService
    (no mock in the production path)."""

    def __init__(self, *, gateway=None, tracer=None, auditor=None):
        self._gateway = gateway
        self.tracer = tracer
        self.auditor = auditor

    def _get_gateway(self):
        if self._gateway is not None:
            return self._gateway
        from app.dependencies import get_services
        return get_services().model_gateway

    async def profile(
        self,
        project_id: str,
        *,
        facts: dict,
        upstream: Optional[dict] = None,
        run_id: Optional[str] = None,
        stage: str = "p1",
        strategy_id: str = "system-default",
        system_prompt: Optional[str] = None,
        skill_body: str = "",
        context_package: Optional[dict] = None,
    ) -> ProfilingResult:
        """Run the P1 建档 identification. Returns ProfilingResult (completed/blocked/failed).

        `facts` = the deterministic采集事实包 (file index / structure / dependency &
        config & test candidates with redacted raw contents / ext counts).
        `upstream` = P0 已 LLM 产出的识别结论 (primary_language / environment clues / DB /
        availability) + source_index summary — REUSED as the建档 baseline (WP-2).
        """
        gw = self._get_gateway()

        readiness = gw.stage_model_readiness(strategy_id=strategy_id, project_id=project_id,
                                             require_tool_calling=True)
        if not readiness.get("available"):
            self._trace("P1 profiling blocked: no model", project_id, run_id, stage)
            return ProfilingResult(
                status="blocked",
                reason=("no_model_key: P1 建档识别需要 LLM 支持，请配置有效 API Key（P1 不降级为规则识别）"
                        f"；{readiness.get('reason','')}"),
                attempted_chain=readiness.get("attempted_chain", []),
                model_error_category="model_unavailable",
                model_user_actions=readiness.get("user_actions", []))

        context_refs, skill_refs = self._context_refs(context_package)
        head_parts = [p for p in (system_prompt, skill_body) if p]
        system_content = ("\n\n---\n\n".join(head_parts) + "\n\n---\n\n" + _SYSTEM_PROMPT
                          if head_parts else _SYSTEM_PROMPT)

        # 批2 (D-110): P1 从单次 chat → 工具循环 Node Worker Agent。事实包 + 上游 P0 结论仍作 user
        # 提示帮助，agent 可按需 list_files/code_grep/fs_read 探读真实源深化建档、多轮推理，末轮产出
        # 结构化建档契约（契约不变，D-108）。走 call_stream 天然读项目模型选择。
        from app.services.stage_agent_loop import run_stage_tool_loop
        loop = await run_stage_tool_loop(
            gw, system_content=system_content,
            user_content=self._build_user_prompt(facts, upstream or {}),
            project_id=project_id, run_id=run_id or "", stage=stage,
            strategy_id=strategy_id, max_tokens=_PROFILING_MAX_TOKENS, temperature=0.3,
            timeout=_PROFILING_TIMEOUT, tracer=self.tracer)
        if loop["status"] != "completed":
            reason = loop.get("error_message") or loop.get("error_category") or "model_call_failed"
            self._trace(f"P1 profiling model call not completed: {reason}", project_id, run_id, stage)
            return ProfilingResult(status="failed", reason=str(reason),
                                   model_used=loop.get("model_used"),
                                   attempted_chain=loop.get("attempted_chain", []),
                                   model_error_category=loop.get("error_category", "model_unavailable"),
                                   model_user_actions=_MODEL_USER_ACTIONS)

        parsed = self._parse(loop.get("content", ""), model_used=loop.get("model_used"))
        self._trace("P1 profiling completed (LLM identification)", project_id, run_id, stage)
        return ProfilingResult(
            status="completed", identification=parsed, model_used=loop.get("model_used"),
            context_refs=context_refs, skill_refs=skill_refs,
        )

    @staticmethod
    def _context_refs(context_package: Optional[dict]) -> tuple[list, list]:
        if not context_package:
            return [], []
        trace = context_package.get("assembly_trace", {}) or {}
        context_refs = list(trace.get("layers_assembled", []))
        skill_refs = [s.get("skill_id") or s.get("name")
                      for s in (context_package.get("skills") or [])
                      if s.get("skill_id") or s.get("name")]
        return context_refs, skill_refs

    def _build_user_prompt(self, facts: dict, upstream: dict) -> str:
        """Build the user message from the采集事实包 + 上游 P0 产物 (bounded, redacted)."""
        facts_blob = json.dumps(facts, ensure_ascii=False, default=str)
        if len(facts_blob) > 22000:
            facts_blob = facts_blob[:22000] + '\n…[事实包超长已截断，请就已给事实推理并在 uncertainty 中声明截断]'
        up_blob = json.dumps(upstream, ensure_ascii=False, default=str)
        if len(up_blob) > 6000:
            up_blob = up_blob[:6000] + '\n…[上游产物已截断]'
        return (
            "以下是平台确定性工具采集的目标项目【建档事实包】（已脱敏、大小写不敏感列举、依赖/配置/测试为"
            "全候选交你判定），以及【上游 P0 由 LLM 产出的接入识别结论】（作为建档基线，须复用而非重算）。\n\n"
            f"【上游 P0 识别结论（复用基线）】：\n{up_blob}\n\n"
            f"【P1 采集事实包】：\n{facts_blob}\n\n"
            "要求：primary_language/技术栈复用 P0 结论（除非有显式冲突并在 uncertainty 登记）；entry_points/"
            "依赖/配置只能引用事实包中真实存在的路径（勿杜撰）；缺失诚实标 null + 原因；主动在 "
            "uncertainty_manifest 中发声识别盲区与任何与 P0 的冲突。严格输出上述 JSON。"
        )

    @staticmethod
    def _scan_json_shape(text: str) -> tuple[int, bool]:
        """扫描 JSON 文本的结构收敛状态：返回 (未闭合的括号深度, 是否停在字符串内部)。

        纯诊断用，不做任何修补（同 acceptance_baseline_service 范式，D-06 同族）——只用来区分
        「输出被截断（结构未闭合）」与「输出完整但非法」这两种处置完全不同的失败。
        """
        depth = 0
        in_string = False
        escaped = False
        for ch in text:
            if in_string:
                if escaped:
                    escaped = False
                elif ch == "\\":
                    escaped = True
                elif ch == '"':
                    in_string = False
                continue
            if ch == '"':
                in_string = True
            elif ch in "{[":
                depth += 1
            elif ch in "}]":
                depth -= 1
        return depth, in_string

    def _diagnose_parse_failure(self, text: str) -> dict:
        """构造可诊断信息（D-06）：响应字符长度 + 是否疑似截断 + 本次预算取值。让"解析失败"
        不再只是一句 parse_error——读产物/日志的人能分辨是「被截断」还是「输出非法 JSON」。"""
        depth, in_string = self._scan_json_shape(text)
        signals: list[str] = []
        if not text:
            signals.append("empty_content: 响应为空（可能推理链耗尽输出预算后无最终文本）")
        if in_string:
            signals.append("unclosed_string: 文本末尾停在未闭合的字符串内")
        if depth > 0:
            signals.append(f"unbalanced_depth={depth}: 有 {depth} 层 {{/[ 未闭合")
        if text and not text.rstrip().endswith(("}", "]")):
            signals.append("tail_not_closed: 末尾字符不是 } 或 ]")
        return {
            "content_len": len(text),
            "suspected_truncation": bool(signals),
            "truncation_signals": signals,
            "tail_snippet": text[-80:] if text else "",
            "max_tokens": _PROFILING_MAX_TOKENS,
            "timeout_s": _PROFILING_TIMEOUT,
            "env_knobs": "P1_PROFILING_MAX_TOKENS / P1_PROFILING_TIMEOUT",
        }

    def _parse(self, content: str, *, model_used: Optional[str] = None) -> dict:
        from app.services.stage_agent_loop import extract_json_object
        data = extract_json_object(content)
        if data is not None:
            return data
        text = (content or "").strip()
        diagnosis = self._diagnose_parse_failure(text)
        if diagnosis["suspected_truncation"]:
            # 截断：可操作结论是「提高输出预算」，用 error 级并直接给出旋钮（D-06）。
            logger.error(
                "P1 profiling: LLM 输出**疑似被截断**导致 JSON 解析失败（D-06 同族）—— "
                "响应长度=%d 字符, 截断信号=%s, 尾部=%r, model=%s, "
                "本次预算 max_tokens=%s / timeout=%ss（可经 %s 调整）",
                diagnosis["content_len"], diagnosis["truncation_signals"],
                diagnosis["tail_snippet"], model_used, diagnosis["max_tokens"],
                diagnosis["timeout_s"], diagnosis["env_knobs"])
        else:
            logger.warning(
                "P1 profiling: LLM 输出**结构已收敛但非法 JSON**（非截断，需修 prompt 契约）—— "
                "响应长度=%d 字符, 尾部=%r, model=%s",
                diagnosis["content_len"], diagnosis["tail_snippet"], model_used)
        return {"parse_error": True, "raw": text[:2000], "parse_diagnosis": diagnosis}

    def _trace(self, summary: str, project_id, run_id, stage) -> None:
        if self.tracer is None:
            return
        try:
            self.tracer.write("model_call", action="p1_profiling", summary=summary,
                              project_id=project_id, run_id=run_id, stage=stage)
        except Exception:
            logger.debug("P1 profiling trace 写入失败（advisory）", exc_info=True)
