"""001_initial_r6_models

Revision ID: 2ca8561394ae
Revises: 
Create Date: 2026-06-25 17:51:04.517929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca8561394ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_definition',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('agent_type', sa.Enum('node_worker', 'acceptance', 'auto_review', 'expert', 'conversation_gate', name='agenttype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'deprecated', 'disabled', name='definitionstatus'), nullable=False),
    sa.Column('responsibilities', sa.Text(), nullable=False),
    sa.Column('forbidden', sa.Text(), nullable=False),
    sa.Column('context_recipe_ref', sa.String(length=255), nullable=True),
    sa.Column('memory_policy_ref', sa.String(length=255), nullable=True),
    sa.Column('model_policy_ref', sa.String(length=255), nullable=True),
    sa.Column('gate_rules', sa.Text(), nullable=False),
    sa.Column('failure_escalation', sa.Text(), nullable=False),
    sa.Column('tool_policy_ref', sa.String(length=255), nullable=True),
    sa.Column('skill_policy_ref', sa.String(length=255), nullable=True),
    sa.Column('mcp_policy_ref', sa.String(length=255), nullable=True),
    sa.Column('input_output_contract', sa.Text(), nullable=False),
    sa.Column('artifact_evidence_contract', sa.Text(), nullable=False),
    sa.Column('self_check_acceptance', sa.Text(), nullable=False),
    sa.Column('context_recipe', sa.JSON(), nullable=True),
    sa.Column('memory_policy', sa.JSON(), nullable=True),
    sa.Column('credential_ref', sa.String(length=255), nullable=True),
    sa.Column('source_status', sa.String(length=50), nullable=False),
    sa.Column('capability_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('credential',
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('key_source', sa.Enum('system', 'tenant', 'user', 'byok', 'env_fallback', name='keysource'), nullable=False),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=False),
    sa.Column('key_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'rotated', 'revoked', name='credentialstatus'), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('credential_id')
    )
    op.create_table('resource_entry',
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.Enum('agent', 'skill', 'tool', 'hook', 'case', 'knowledge', 'template', 'mcp', 'expert_agent', 'policy', 'deterministic_transformer', 'execution_provider', name='resourcetype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.Enum('internal_current', 'internal_archive', 'user_provided', 'community', 'external_online', 'third_party', 'generated', name='sourcetype'), nullable=False),
    sa.Column('source_trust_level', sa.Enum('trusted_current', 'reviewed_reference', 'read_only_reference', 'unreviewed', 'blocked', 'unknown', name='trustlevel'), nullable=False),
    sa.Column('source_path_or_ref', sa.String(length=500), nullable=True),
    sa.Column('risk_level', sa.Enum('L0', 'L1', 'L2', 'L3', 'L4', 'L5', name='risklevel'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'read_only', 'planned', 'local_existing', 'externally_available', 'not_connected', 'deprecated', 'superseded', 'disabled', 'blocked', 'archived', name='resourcestatus'), nullable=False),
    sa.Column('permission_scope', sa.String(length=100), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('allowed_actions', sa.JSON(), nullable=True),
    sa.Column('blocked_actions', sa.JSON(), nullable=True),
    sa.Column('input_contract', sa.Text(), nullable=False),
    sa.Column('output_contract', sa.Text(), nullable=False),
    sa.Column('artifact_evidence_contract', sa.Text(), nullable=False),
    sa.Column('gate_policy', sa.Text(), nullable=False),
    sa.Column('trace_policy', sa.String(length=50), nullable=False),
    sa.Column('audit_policy', sa.String(length=50), nullable=False),
    sa.Column('credential_ref', sa.String(length=255), nullable=True),
    sa.Column('supersedes', sa.String(length=255), nullable=True),
    sa.Column('superseded_by', sa.String(length=255), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=False),
    sa.Column('type_metadata', sa.JSON(), nullable=True),
    sa.Column('source_status', sa.String(length=50), nullable=False),
    sa.Column('capability_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_table('skill_definition',
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('series', sa.Enum('R', 'P', name='skillseries'), nullable=False),
    sa.Column('category', sa.Enum('stage_skill', 'planning_skill', 'execution_skill', 'validation_skill', 'review_skill', 'resource_skill', 'documentation_skill', 'handoff_skill', 'construction_skill', name='skillcategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_model_policy', sa.String(length=255), nullable=True),
    sa.Column('required_tools', sa.JSON(), nullable=True),
    sa.Column('required_context', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'planned', 'platform_runtime', 'not_active_in_local_agent', 'deprecated', 'disabled', name='skillstatus'), nullable=False),
    sa.Column('skill_source', sa.String(length=100), nullable=True),
    sa.Column('source_status', sa.String(length=50), nullable=False),
    sa.Column('capability_status', sa.String(length=50), nullable=False),
    sa.Column('directory_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_definition')
    op.drop_table('resource_entry')
    op.drop_table('credential')
    op.drop_table('agent_definition')
    # ### end Alembic commands ###
