"""r9_run_and_gate_tables

Revision ID: 3a72e126a753
Revises: 58ae31ca2d2b
Create Date: 2026-06-27 22:31:22.275250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a72e126a753'
down_revision: Union[str, None] = '58ae31ca2d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
