"""R9-3A: add coding_agent_ref to Project

Revision ID: 58ae31ca2d2b
Revises: 2a3b4c5d6e7f
Create Date: 2026-06-27 12:50:42.101597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ae31ca2d2b'
down_revision: Union[str, None] = '2a3b4c5d6e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_definition', 'category',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('system', 'expert', name='agentcategory'),
               nullable=False,
               existing_server_default=sa.text("'system'"))
    op.alter_column('agent_definition', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('agent_definition', 'origin',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'user_created'"))
    op.add_column('project', sa.Column('coding_agent_ref', sa.String(length=36), nullable=True))
    op.alter_column('skill_definition', 'category',
               existing_type=sa.VARCHAR(length=19),
               type_=sa.Enum('common', 'p0', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'other', name='skillcategory'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skill_definition', 'category',
               existing_type=sa.Enum('common', 'p0', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'other', name='skillcategory'),
               type_=sa.VARCHAR(length=19),
               existing_nullable=False)
    op.drop_column('project', 'coding_agent_ref')
    op.alter_column('agent_definition', 'origin',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'user_created'"))
    op.alter_column('agent_definition', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('agent_definition', 'category',
               existing_type=sa.Enum('system', 'expert', name='agentcategory'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'system'"))
    # ### end Alembic commands ###
